default:
    outputs:
        dev:
            type: duckdb
            path: /tmp/duck.db
            threads: 8
            extensions:
                - httpfs
                - parquet
            external_root: s3://data
            settings:
                s3_endpoint: "minio:9020"
                s3_access_key_id: minio
                s3_secret_access_key: minio123
                s3_url_style: path
                s3_use_ssl: false
    target: dev

config:
    send_anonymous_usage_stats: False
    use_colors: True
