version: "3.9"
services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        image: ubuntu
        volumes:
            - /var/run/docker.sock:/var/run/docker-host.sock
            - .:/workspace:cached
    # clickhouse:
    #     image: clickhouse/clickhouse-server:22.12.1
    #     ports:
    #         - 9000:9000
    #         - 8123:8123
    #         - 9363:9363
    #     volumes:
    #         - .clickhouse:/var/lib/clickhouse
    #         - ./clickhouse/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml
    #         - ./clickhouse/tabix.xml:/etc/clickhouse-server/config.d/tabix.xml
    #     ulimits:
    #         nofile:
    #             soft: 262144
    #             hard: 262144
    # grafana:
    #     image: grafana/grafana:9.3.2
    #     user: ":"
    #     volumes:
    #         - ./grafana/:/etc/grafana/provisioning/datasources:rw
    #         - .grafana:/var/lib/grafana:rw
    #     ports:
    #         - 3000:3000
    #     environment:
    #         - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    #         - GF_AUTH_DISABLE_LOGIN_FORM=true
    #         - GF_AUTH_ANONYMOUS_ENABLED=true
    #         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    # prometheus:
    #     image: prom/prometheus:v2.41.0
    #     volumes:
    #         - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #     ports:
    #         - 9090:9090
    minio:
        image: minio/minio
        volumes:
            - .minio/:/data
        ports:
            - "9000:9000"
            - "9090:9090"
        command: [ "server", "/data", "--console-address", ":9090" ]
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: minio_secret_key
