version: "3.9"
services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        image: ubuntu
        volumes:
            - .:/workspace:cached
    clickhouse:
        image: clickhouse/clickhouse-server:22.3.11.12
        ports:
            - 9000:9000
            - 8123:8123
            - 9363:9363
        volumes:
            - .clickhouse:/var/lib/clickhouse
            - ./clickhouse/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml
            - ./clickhouse/tabix.xml:/etc/clickhouse-server/config.d/tabix.xml
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
    grafana:
        image: grafana/grafana
        user: ":"
        volumes:
            - ./grafana/:/etc/grafana/provisioning/datasources:rw
            - .grafana:/var/lib/grafana:rw
        ports:
            - 3000:3000
        environment:
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    prometheus:
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        image: prom/prometheus
        ports:
            - 9090:9090
