version: "3.9"
services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        volumes:
            - .:/workspace:cached
    clickhouse:
        image: yandex/clickhouse-server:21.3.20.1
        ports:
            - 9000:9000
            - 8123:8123
        volumes:
            - .clickhouse:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
    grafana:
        image: grafana/grafana
        user: ":"
        volumes:
            - ./grafana/:/etc/grafana/provisioning/datasources:rw
            - .grafana:/var/lib/grafana:rw
        ports:
            - 3000:3000
        environment:
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
