version: "3.9"
services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        image: ubuntu
        volumes:
            - /var/run/docker.sock:/var/run/docker-host.sock
            - .:/workspace:cached
    rill:
        image: rilldata/rill:latest
        volumes:
            - ./rill/:/rill
        ports:
            - "9009:9009"
        command: [ "start", "--project", "/rill" ]
    minio:
        image: minio/minio
        volumes:
            - .minio/:/data
        ports:
            - "9010:9010"
            - "9020:9020"
        command:
            [
                "server",
                "/data",
                "--console-address",
                ":9010",
                "--address",
                ":9020"
            ]
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
