version: 2

models:
    - name: my_python_model

      # Document within the same codebase
      description: My transformation written in Python

      # Configure in ways that feel intuitive and familiar
      config:
          materialized: table
          tags: ["python"]
