version: 2

models:
    - name: custom_hits
      description: "A starter dbt model"
      columns:
          - name: WatchID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

sources:
    - name: main
      meta:
          external_location: "s3://data/{name}.parquet"
      tables:
          - name: hits
